import {
  CreditCard,
  Car,
  HeartHandshake,
  FileText,
  Home,
  User,
  ShieldCheck,
  RotateCcw,
  CheckCircle,
  Folder,
  Save,
  Building2,
  MessageSquarePlus,
  ClipboardList,
  Map,
  Bell,
  Search,
  ArrowRight,
  ExternalLink,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  X,
  AlertTriangle,
  Globe,
  Lock,
  Mic,
  MapPin,
  Filter,
  GraduationCap,
  HeartPulse,
  BarChart3,
  Clock,
  BadgeCheck,
  Check,
  Share2,
  Square,
  Menu,
  LogOut,
  Settings,
  Sparkles,
  Cpu,
  Activity,
  Database,
  Network,
  Terminal,
  Zap
} from "lucide-react";

const iconMap = {
  menu: Menu,
  hamburger: Menu,
  logout: LogOut,
  settings: Settings,
  identity: CreditCard,
  id: CreditCard,
  creditcard: CreditCard,
  transport: Car,
  car: Car,
  welfare: HeartHandshake,
  hearthandshake: HeartHandshake,
  handheart: HeartHandshake,
  document: FileText,
  documents: FileText,
  filetext: FileText,
  home: Home,
  user: User,
  profile: User,
  shield: ShieldCheck,
  refresh: RotateCcw,
  check: CheckCircle,
  checkCircle: CheckCircle,
  checkMark: Check,
  folder: Folder,
  save: Save,
  building: Building2,
  government: Building2,
  request: MessageSquarePlus,
  requests: MessageSquarePlus,
  development: Building2,
  insights: BarChart3,
  applications: ClipboardList,
  clipboard: ClipboardList,
  map: Map,
  bell: Bell,
  notifications: Bell,
  search: Search,
  arrow: ArrowRight,
  arrowRight: ArrowRight,
  external: ExternalLink,
  chevron: ChevronDown,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  x: X,
  close: X,
  alert: AlertTriangle,
  warning: AlertTriangle,
  globe: Globe,
  lock: Lock,
  mic: Mic,
  pin: MapPin,
  filter: Filter,
  education: GraduationCap,
  health: HeartPulse,
  healthcare: HeartPulse,
  analytics: BarChart3,
  clock: Clock,
  badgeCheck: BadgeCheck,
  share: Share2,
  square: Square,
  stop: Square,
  sparkles: Sparkles,
  ai: Sparkles,
  cpu: Cpu,
  engine: Cpu,
  translation: Cpu,
  activity: Activity,
  gateway: Activity,
  database: Database,
  network: Network,
  terminal: Terminal,
  zap: Zap
};

export default function UiIcon({ name, size = 18, className = "", "aria-label": ariaLabel, ...rest }) {
  const IconComponent = iconMap[String(name).toLowerCase()] || FileText;
  return (
    <IconComponent
      size={size}
      className={className}
      aria-label={ariaLabel}
      aria-hidden={!ariaLabel}
      strokeWidth={1.8}
      {...rest}
    />
  );
}

export { iconMap };
